const LocalIcons = {
    FITBIT_ICON: "../assets/images/FitbitIcon.svg",
    BANNER: "../assets/images/banner.jpg",
    PLAY: "../assets/images/pay.svg",
    NIKE: "../assets/images/nike.svg",
    ADIDAS: "../assets/images/adidas.svg",
    PUMA: "../assets/images/puma.svg",
    HICON: "../assets/images/hicon.svg",
    ACTIVITY1: "../assets/images/activity1.jpg",
    ACTIVITY2: "../assets/images/activity2.jpg",
    ACTIVITY3: "../assets/images/activity3.jpg",
    ACTIVITY4: "../assets/images/activity4.jpg",
    ABOUT_US: "../assets/images/aboutus.jpg",
    Shoes: '../assets/images/shoes.svg',
    Image2: '../assets/images/image2.svg',
    Image3: '../assets/images/image3.svg',
    Image4: '../assets/images/image4.svg',
    Image5: '../assets/images/image5.svg',
    Image6: '../assets/images/image6.svg',
    OURBLOG1:"../assets/images/blog1.jpg",
    OURBLOG2:"../assets/images/blog2.jpg",
    OURBLOG3:"../assets/images/blog3.jpg",
    BANNERVIDEO:"../assets/images/banner.mp4"
}
export default LocalIcons